import { NextResponse } from 'next/server';
import { dbQuery, withTransaction } from '@/lib/server-db';
import { exigirPermissao, respostaAutorizacao } from '@/lib/server-auth';
export const runtime = 'nodejs';
type FuncionarioInput={processo?:string;nome?:string;nuit?:string;bi?:string;contacto?:string;departamentoId?:string|null;departamento?:string|null;cargo?:string;tipoContrato?:'Permanente'|'Contratado';admissao?:string;fimContrato?:string|null};
const texto=(v:unknown)=>typeof v==='string'?v.trim():'';
const dataValida=(v:string)=>/^\d{4}-\d{2}-\d{2}$/.test(v);
async function normalizarDepartamento(input:FuncionarioInput){const id=texto(input.departamentoId);if(id)return id;const nome=texto(input.departamento);if(!nome)return null;const r=await dbQuery<{id:string}>('select id from departamentos where lower(nome)=lower($1) and ativo=true limit 1',[nome]);if(!r.rows[0])throw new Error('DEPARTAMENTO_INVALIDO');return r.rows[0].id;}
function validar(input:FuncionarioInput){const processo=texto(input.processo),nome=texto(input.nome),tipoContrato=input.tipoContrato,admissao=texto(input.admissao),fimContrato=input.fimContrato?texto(input.fimContrato):null;if(!processo||!nome||!tipoContrato||!admissao)throw new Error('DADOS_OBRIGATORIOS');if(!['Permanente','Contratado'].includes(tipoContrato))throw new Error('TIPO_CONTRATO_INVALIDO');if(!dataValida(admissao))throw new Error('DATA_ADMISSAO_INVALIDA');if(fimContrato&&!dataValida(fimContrato))throw new Error('FIM_CONTRATO_INVALIDO');if(tipoContrato==='Contratado'&&!fimContrato)throw new Error('FIM_CONTRATO_OBRIGATORIO');if(fimContrato&&fimContrato<admissao)throw new Error('DATAS_INVALIDAS');return{processo,nome,tipoContrato,admissao,fimContrato};}
function mensagemErro(e:unknown){const c=e instanceof Error?e.message:'';const m:Record<string,string>={DADOS_OBRIGATORIOS:'Processo, nome, tipo de contrato e data de admissão são obrigatórios.',TIPO_CONTRATO_INVALIDO:'Tipo de contrato inválido.',DATA_ADMISSAO_INVALIDA:'Data de admissão inválida.',FIM_CONTRATO_INVALIDO:'Fim de contrato inválido.',FIM_CONTRATO_OBRIGATORIO:'O contrato Contratado precisa de data de fim.',DATAS_INVALIDAS:'O fim do contrato não pode ser anterior à admissão.',DEPARTAMENTO_INVALIDO:'Departamento não encontrado ou inativo.'};return m[c]||'Não foi possível concluir a operação.';}
export async function GET(){try{await exigirPermissao('funcionarios');const r=await dbQuery(`select f.id,f.processo,f.nome,f.nuit,f.bi,f.contacto,f.departamento_id as "departamentoId",d.nome as departamento,f.cargo,f.tipo_contrato as "tipoContrato",f.data_admissao as admissao,f.fim_contrato as "fimContrato",f.ativo,f.versao,f.criado_em as "criadoEm",f.atualizado_em as "atualizadoEm" from funcionarios f left join departamentos d on d.id=f.departamento_id where f.ativo=true order by f.nome asc`);return NextResponse.json({ok:true,funcionarios:r.rows});}catch(e){if(e instanceof Error&&['UNAUTHORIZED','FORBIDDEN'].includes(e.message))return respostaAutorizacao(e);console.error('GET /api/funcionarios',e);return NextResponse.json({ok:false,erro:'Não foi possível carregar os funcionários.'},{status:500});}}
export async function POST(request:Request){try{const sessao=await exigirPermissao('funcionarios');const input=await request.json() as FuncionarioInput;const dados=validar(input),departamentoId=await normalizarDepartamento(input);const funcionario=await withTransaction(async client=>{const r=await client.query(`insert into funcionarios(processo,nome,nuit,bi,contacto,departamento_id,cargo,tipo_contrato,data_admissao,fim_contrato,criado_por,atualizado_por,atualizado_em) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$11,CURRENT_TIMESTAMP) returning id,processo,nome,nuit,bi,contacto,departamento_id as "departamentoId",cargo,tipo_contrato as "tipoContrato",data_admissao as admissao,fim_contrato as "fimContrato",ativo,versao,criado_em as "criadoEm",atualizado_em as "atualizadoEm"`,[dados.processo,dados.nome,texto(input.nuit)||null,texto(input.bi)||null,texto(input.contacto)||null,departamentoId,texto(input.cargo)||null,dados.tipoContrato,dados.admissao,dados.fimContrato,sessao.utilizadorId]);const novo=r.rows[0];await client.query(`insert into auditoria(entidade,entidade_id,operacao,utilizador_id,dispositivo_id,origem,depois) values('funcionario',$1,'CREATE',$2,$3,'online',$4)`,[novo.id,sessao.utilizadorId,request.headers.get('x-device-id')||null,JSON.stringify(novo)]);return novo;});return NextResponse.json({ok:true,funcionario},{status:201});}catch(e){if(e instanceof Error&&['UNAUTHORIZED','FORBIDDEN'].includes(e.message))return respostaAutorizacao(e);if(e instanceof Error&&(e.message==='23505'||e.message.includes('UNIQUE constraint failed')))return NextResponse.json({ok:false,erro:'Já existe um funcionário com esse número de processo.'},{status:409});if(e instanceof Error&&['DADOS_OBRIGATORIOS','TIPO_CONTRATO_INVALIDO','DATA_ADMISSAO_INVALIDA','FIM_CONTRATO_INVALIDO','FIM_CONTRATO_OBRIGATORIO','DATAS_INVALIDAS','DEPARTAMENTO_INVALIDO'].includes(e.message))return NextResponse.json({ok:false,erro:mensagemErro(e)},{status:400});console.error('POST /api/funcionarios',e);return NextResponse.json({ok:false,erro:mensagemErro(e)},{status:500});}}
