import { NextResponse } from 'next/server';
import { withTransaction } from '@/lib/server-db';
import { exigirPermissao, respostaAutorizacao } from '@/lib/server-auth';
export const runtime='nodejs';
type Input={inicio?:string;fim?:string;dias?:number;estado?:string};
const data=(v:unknown)=>typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v)?v:'';
const local=()=> (process.env.DATABASE_MODE||'local').toLowerCase()==='local';
const auditJson=(n:number)=>local()?`$${n}`:`$${n}::jsonb`;
export async function PUT(request:Request,{params}:{params:Promise<{id:string}>}){try{const sessao=await exigirPermissao('ferias');const {id}=await params;const i=await request.json() as Input;const inicio=data(i.inicio),fim=data(i.fim),dias=Number(i.dias||0);if(!inicio||!fim||fim<inicio||!Number.isInteger(dias)||dias<=0)return NextResponse.json({ok:false,erro:'Dados das férias inválidos.'},{status:400});const r=await withTransaction(async client=>{const old=await client.query('select * from ferias where id=$1'+(local()?'':' for update'),[id]);if(!old.rows[0])throw new Error('NAO_ENCONTRADO');const u=await client.query(`update ferias set inicio=$1,fim=$2,dias=$3,estado=$4,atualizado_por=$5,atualizado_em=CURRENT_TIMESTAMP,versao=versao+1 where id=$6 returning id,funcionario_id as "funcionarioId",inicio,fim,dias,estado,versao,atualizado_em as "atualizadoEm"`,[inicio,fim,dias,i.estado||'Disponível',sessao.utilizadorId,id]);const n=u.rows[0];await client.query(`insert into auditoria(entidade,entidade_id,operacao,utilizador_id,origem,antes,depois) values('ferias',$1,'UPDATE',$2,'online',${auditJson(3)},${auditJson(4)})`,[id,sessao.utilizadorId,JSON.stringify(old.rows[0]),JSON.stringify(n)]);return n;});return NextResponse.json({ok:true,ferias:r});}catch(e){if(e instanceof Error&&['UNAUTHORIZED','FORBIDDEN'].includes(e.message))return respostaAutorizacao(e);if(e instanceof Error&&e.message==='NAO_ENCONTRADO')return NextResponse.json({ok:false,erro:'Férias não encontradas.'},{status:404});console.error('PUT /api/ferias/[id]',e);return NextResponse.json({ok:false,erro:'Não foi possível atualizar as férias.'},{status:500});}}
export async function DELETE(request:Request,{params}:{params:Promise<{id:string}>}){try{const sessao=await exigirPermissao('ferias');const {id}=await params;await withTransaction(async client=>{const old=await client.query('select * from ferias where id=$1'+(local()?'':' for update'),[id]);if(!old.rows[0])throw new Error('NAO_ENCONTRADO');await client.query('delete from ferias where id=$1',[id]);await client.query(`insert into auditoria(entidade,entidade_id,operacao,utilizador_id,origem,antes) values('ferias',$1,'DELETE',$2,'online',${auditJson(3)})`,[id,sessao.utilizadorId,JSON.stringify(old.rows[0])]);});return NextResponse.json({ok:true});}catch(e){if(e instanceof Error&&['UNAUTHORIZED','FORBIDDEN'].includes(e.message))return respostaAutorizacao(e);if(e instanceof Error&&e.message==='NAO_ENCONTRADO')return NextResponse.json({ok:false,erro:'Férias não encontradas.'},{status:404});console.error('DELETE /api/ferias/[id]',e);return NextResponse.json({ok:false,erro:'Não foi possível eliminar as férias.'},{status:500});}}
