'use client';

import { useEffect, useMemo, useState } from 'react';
import { direitoAcumulado, diasUtilizadosReal, diasVencidos, resumoAnual, STORAGE_FERIAS, type FuncionarioFerias } from '../../lib/ferias';

type Historico = { inicio: string; fim: string; dias: number; estado: string };
type Funcionario = FuncionarioFerias & { nuit: string; bi: string; contacto: string; departamento: string };
const departamentos = ['Administração','Serração','Vendas','Carpintaria','Manutenção','Mecânica','Seguranças'];
function formatar(s:string){if(!s)return'—';const[a,m,d]=s.split('-');return`${d}/${m}/${a}`;}

export default function RelatoriosPage(){
 const[funcionarios,setFuncionarios]=useState<Funcionario[]>([]);const[tipo,setTipo]=useState('funcionario');const[filtro,setFiltro]=useState('');const[de,setDe]=useState('');const[ate,setAte]=useState('');
 useEffect(()=>{try{const v=localStorage.getItem(STORAGE_FERIAS);if(v){const lista=JSON.parse(v) as Partial<Funcionario>[];setFuncionarios(lista.map(f=>({...f,nuit:f.nuit||'',bi:f.bi||'',historico:f.historico||[]} as Funcionario)));}}catch{}},[]);
 const lista=useMemo(()=>funcionarios.filter(f=>{const texto=!filtro||f.nome.toLowerCase().includes(filtro.toLowerCase())||f.processo.includes(filtro)||f.departamento===filtro;const hist=(f.historico||[]).filter(h=>(!de||h.inicio>=de)&&(!ate||h.fim<=ate));return texto&&((!de&&!ate)||hist.length>0);}),[funcionarios,filtro,de,ate]);
 return <main><div className="container"><section className="hero"><h1>Relatórios</h1><p>Consulte férias, saldos, vencimentos e histórico por funcionário, departamento e período.</p></section>
 <section className="section card"><div className="form-grid"><label>Tipo de relatório<select value={tipo} onChange={e=>{setTipo(e.target.value);setFiltro('');setDe('');setAte('')}}><option value="funcionario">Por funcionário</option><option value="departamento">Por departamento</option><option value="periodo">Por período</option></select></label>{tipo==='funcionario'&&<label>Funcionário<select value={filtro} onChange={e=>setFiltro(e.target.value)}><option value="">Todos</option>{funcionarios.map(f=><option key={f.processo} value={f.processo}>{f.processo} — {f.nome}</option>)}</select></label>}{tipo==='departamento'&&<label>Departamento<select value={filtro} onChange={e=>setFiltro(e.target.value)}><option value="">Todos</option>{departamentos.map(d=><option key={d}>{d}</option>)}</select></label>}{tipo==='periodo'&&<><label>Data inicial<input type="date" value={de} onChange={e=>setDe(e.target.value)}/></label><label>Data final<input type="date" value={ate} onChange={e=>setAte(e.target.value)}/></label></>}</div></section>
 <section className="section"><h2>Resultado</h2>{lista.length===0?<p className="empty-state">Nenhum resultado para os filtros selecionados.</p>:<div className="table-wrapper"><table><thead><tr><th>Processo</th><th>Funcionário</th><th>NUIT</th><th>Número de BI</th><th>Departamento</th><th>Contrato</th><th>Direito</th><th>Utilizados</th><th>Saldo</th><th>Vencidos</th><th>Histórico</th></tr></thead><tbody>{lista.map(f=><tr key={f.processo}><td>{f.processo}</td><td><strong>{f.nome}</strong></td><td>{f.nuit||'—'}</td><td>{f.bi||'—'}</td><td>{f.departamento}</td><td>{f.tipoContrato}</td><td>{direitoAcumulado(f)} dias</td><td>{diasUtilizadosReal(f)} dias</td><td><strong>{Math.max(0,direitoAcumulado(f)-diasUtilizadosReal(f))} dias</strong></td><td>{diasVencidos(f)} dias</td><td>{(f.historico||[]).length} registo(s)</td></tr>)}</tbody></table></div>}</section>
 <section className="section"><h2>Resumo anual</h2>{lista.length===0?<p className="empty-state">Nenhum funcionário disponível.</p>:<div className="history-list">{lista.map(f=><div className="card" key={`anual-${f.processo}`}><h3 style={{marginTop:0}}>Processo {f.processo} — {f.nome}</h3><p>NUIT: {f.nuit||'—'} · BI: {f.bi||'—'} · Direito: <strong>{direitoAcumulado(f)} dias</strong> · Utilizado: <strong>{diasUtilizadosReal(f)} dias</strong> · Saldo: <strong>{Math.max(0,direitoAcumulado(f)-diasUtilizadosReal(f))} dias</strong></p><div className="table-wrapper"><table><thead><tr><th>Ano</th><th>Dias adquiridos</th><th>Dias utilizados</th><th>Saldo do ano</th><th>Saldo acumulado</th></tr></thead><tbody>{resumoAnual(f).map(item=><tr key={`${f.processo}-${item.ano}`}><td><strong>{item.ano}</strong></td><td>{item.ganhou}</td><td>{item.utilizado}</td><td>{item.saldoAno}</td><td><strong>{item.saldoAcumulado}</strong></td></tr>)}</tbody></table></div></div>)}</div>}</section>
 </div></main>;
}
