'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import { adicionarDias, direitoAcumulado, diasUtilizadosReal, estadoFerias, saldoRestante, type FuncionarioFerias } from '../../lib/ferias';

const DEPARTAMENTOS = ['Administração','Serração','Vendas','Carpintaria','Manutenção','Mecânica','Seguranças'];
type Funcionario = FuncionarioFerias & { id?: string; nuit: string; bi: string; contacto: string; departamento: string; departamentoId?: string; versao?: number };
const FORM_INICIAL: Funcionario = { processo:'',nome:'',nuit:'',bi:'',contacto:'',departamento:'Administração',tipoContrato:'Permanente',admissao:'',fimContrato:'',diasUtilizados:0,inicioFerias:'',fimFerias:'',historico:[] };
function formatarData(data:string){if(!data)return '—';const [ano,mes,dia]=data.split('-');return `${dia}/${mes}/${ano}`;}
function mapearFuncionario(item:any):Funcionario{return {...FORM_INICIAL,id:item.id,processo:item.processo||'',nome:item.nome||'',nuit:item.nuit||'',bi:item.bi||'',contacto:item.contacto||'',departamento:item.departamento||'Administração',departamentoId:item.departamentoId,tipoContrato:item.tipoContrato,admissao:item.admissao||'',fimContrato:item.fimContrato||'',versao:item.versao||1};}

export default function FuncionariosPage(){
 const [funcionarios,setFuncionarios]=useState<Funcionario[]>([]);const [carregado,setCarregado]=useState(false);const [form,setForm]=useState<Funcionario>(FORM_INICIAL);const [idEditando,setIdEditando]=useState<string|null>(null);const [mensagem,setMensagem]=useState('');
 async function carregar(){try{const r=await fetch('/api/funcionarios',{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.erro||'Não foi possível carregar os funcionários.');setFuncionarios((d.funcionarios||[]).map(mapearFuncionario));}catch(e){setMensagem(e instanceof Error?e.message:'Não foi possível carregar os funcionários.');}finally{setCarregado(true);}}
 useEffect(()=>{carregar();},[]);
 const total=funcionarios.length;const permanentes=useMemo(()=>funcionarios.filter(i=>i.tipoContrato==='Permanente').length,[funcionarios]);const fimFeriasAutomatico=form.inicioFerias&&Number(form.diasUtilizados||0)>0?adicionarDias(form.inicioFerias,Number(form.diasUtilizados||0)):'';const direitoForm=direitoAcumulado(form);const utilizadoForm=diasUtilizadosReal(form);const saldoForm=saldoRestante(form);
 function atualizarCampo(campo:keyof Funcionario,valor:string|number){setForm(a=>({...a,[campo]:valor}));setMensagem('');}
 function iniciarEdicao(f:Funcionario){setIdEditando(f.id||null);setForm({...FORM_INICIAL,...f,nuit:f.nuit||'',bi:f.bi||'',contacto:f.contacto||''});setMensagem(`A editar o funcionário ${f.processo}.`);window.scrollTo({top:0,behavior:'smooth'});}
 function cancelarEdicao(){setIdEditando(null);setForm(FORM_INICIAL);setMensagem('Edição cancelada.');}
 async function guardarFuncionario(event:FormEvent<HTMLFormElement>){event.preventDefault();setMensagem('');const processo=form.processo.trim(),nome=form.nome.trim(),nuit=form.nuit.trim(),bi=form.bi.trim(),contacto=form.contacto.trim();if(!processo||!nome||!contacto||!form.admissao)return setMensagem('Preencha Número de processo, Nome, Contacto e Data de admissão.');if(form.tipoContrato==='Contratado'&&!form.fimContrato)return setMensagem('Para contrato Contratado, informe a data de fim do contrato.');if(form.fimContrato&&form.fimContrato<form.admissao)return setMensagem('A data de fim do contrato não pode ser anterior à data de admissão.');
  const payload={processo,nome,nuit,bi,contacto,departamento:form.departamento,tipoContrato:form.tipoContrato,admissao:form.admissao,fimContrato:form.tipoContrato==='Permanente'?null:form.fimContrato};
  try{const url=idEditando?`/api/funcionarios/${idEditando}`:'/api/funcionarios';const r=await fetch(url,{method:idEditando?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.erro||'Não foi possível guardar o funcionário.');await carregar();setIdEditando(null);setForm(FORM_INICIAL);setMensagem(idEditando?'Funcionário atualizado com sucesso.':'Funcionário adicionado com sucesso.');}catch(e){setMensagem(e instanceof Error?e.message:'Não foi possível guardar o funcionário.');}
 }
 async function removerFuncionario(f:Funcionario){if(!f.id)return;if(!window.confirm(`Tem certeza que deseja desativar o funcionário ${f.processo}? A operação ficará registada na auditoria.`))return;try{const r=await fetch(`/api/funcionarios/${f.id}`,{method:'DELETE'});const d=await r.json();if(!r.ok)throw new Error(d.erro||'Não foi possível remover o funcionário.');await carregar();if(idEditando===f.id)cancelarEdicao();setMensagem(`Funcionário ${f.processo} desativado.`);}catch(e){setMensagem(e instanceof Error?e.message:'Não foi possível remover o funcionário.');}}
 return <main><div className="container"><div className="hero"><h1>Funcionários</h1><p>Cadastro central dos funcionários. Os dados são guardados no banco local SQLite através da API protegida.</p></div>
  <div className="grid" style={{gridTemplateColumns:'repeat(3,1fr)'}}><div className="card"><span className="card-label">Total de funcionários</span><strong className="card-value">{total}</strong></div><div className="card"><span className="card-label">Permanentes</span><strong className="card-value">{permanentes}</strong></div><div className="card"><span className="card-label">Contratados</span><strong className="card-value">{total-permanentes}</strong></div></div>
  <section className="section"><h2>{idEditando?`Editar funcionário — Processo ${form.processo}`:'Novo funcionário'}</h2><form onSubmit={guardarFuncionario} className="card employee-form"><div className="form-grid"><label>Número de processo<input value={form.processo} onChange={e=>atualizarCampo('processo',e.target.value)} placeholder="Ex.: 0025" disabled={Boolean(idEditando)}/></label><label>Nome completo<input value={form.nome} onChange={e=>atualizarCampo('nome',e.target.value)} placeholder="Nome completo"/></label><label>NUIT<input value={form.nuit} onChange={e=>atualizarCampo('nuit',e.target.value)} placeholder="Número do NUIT"/></label><label>Número de BI<input value={form.bi} onChange={e=>atualizarCampo('bi',e.target.value)} placeholder="Número do BI"/></label><label>Contacto<input value={form.contacto} onChange={e=>atualizarCampo('contacto',e.target.value)} placeholder="Telefone"/></label><label>Departamento<select value={form.departamento} onChange={e=>atualizarCampo('departamento',e.target.value)}>{DEPARTAMENTOS.map(d=><option key={d}>{d}</option>)}</select></label><label>Tipo de contrato<select value={form.tipoContrato} onChange={e=>atualizarCampo('tipoContrato',e.target.value as FuncionarioFerias['tipoContrato'])}><option value="Permanente">Permanente</option><option value="Contratado">Contratado</option></select></label><label>Data de admissão<input type="date" value={form.admissao} onChange={e=>atualizarCampo('admissao',e.target.value)}/></label><label>Fim do contrato<input type="date" value={form.fimContrato} onChange={e=>atualizarCampo('fimContrato',e.target.value)} disabled={form.tipoContrato==='Permanente'}/></label></div>
   <div className="vacation-preview"><strong>Resumo calculado pelo motor de férias</strong><span>Direito acumulado: {direitoForm} dias</span><span>Utilizados: {utilizadoForm} dias</span><span>Saldo disponível: {saldoForm} dias</span><span>Estado: {estadoFerias(form.inicioFerias,fimFeriasAutomatico)}</span></div><div style={{display:'flex',gap:10,flexWrap:'wrap'}}><button className="primary-button" type="submit">{idEditando?'Guardar alterações':'Adicionar funcionário'}</button>{idEditando&&<button className="secondary-button" type="button" onClick={cancelarEdicao}>Cancelar edição</button>}</div>{mensagem&&<p className="form-message">{mensagem}</p>}</form></section>
  <section className="section"><h2>Registo de funcionários</h2>{!carregado?<div className="card empty-state">A carregar dados...</div>:funcionarios.length===0?<div className="card empty-state">Ainda não existem funcionários cadastrados.</div>:<div className="table-wrapper"><table><thead><tr><th>Processo</th><th>Nome</th><th>NUIT</th><th>BI</th><th>Contacto</th><th>Departamento</th><th>Contrato</th><th>Admissão</th><th>Fim contrato</th><th>Direito</th><th>Utilizados</th><th>Saldo</th><th>Ações</th></tr></thead><tbody>{funcionarios.map(f=>{const direito=direitoAcumulado(f),utilizados=diasUtilizadosReal(f),saldo=saldoRestante(f);return <tr key={f.id||f.processo}><td>{f.processo}</td><td><strong>{f.nome}</strong></td><td>{f.nuit||'—'}</td><td>{f.bi||'—'}</td><td>{f.contacto}</td><td><strong>{f.departamento}</strong></td><td><strong>{f.tipoContrato}</strong></td><td>{formatarData(f.admissao)}</td><td>{formatarData(f.fimContrato)}</td><td>{direito} dias</td><td>{utilizados} dias</td><td><strong>{saldo} dias</strong></td><td><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button className="secondary-button" type="button" onClick={()=>iniciarEdicao(f)}>Editar</button><button className="danger-button" type="button" onClick={()=>removerFuncionario(f)}>Remover</button></div></td></tr>})}</tbody></table></div>}</section>
 </div></main>;
}
