-- Schema central do Controlo de Férias RH. Não contém credenciais reais.
create extension if not exists pgcrypto;
create table if not exists departamentos (id uuid primary key default gen_random_uuid(),nome text not null unique,ativo boolean not null default true,criado_em timestamptz not null default now(),atualizado_em timestamptz not null default now());
create table if not exists utilizadores (id uuid primary key default gen_random_uuid(),login text not null,nome text not null,papel text not null check (papel in ('Administrador','RH','Outro')),password_hash text not null,ativo boolean not null default true,versao bigint not null default 1,criado_em timestamptz not null default now(),atualizado_em timestamptz not null default now(),constraint utilizador_login_papel_unique unique(login,papel));
create table if not exists funcionarios (id uuid primary key default gen_random_uuid(),processo text not null unique,nome text not null,nuit text,bi text,contacto text,departamento_id uuid references departamentos(id),cargo text,tipo_contrato text not null check (tipo_contrato in ('Permanente','Contratado')),data_admissao date not null,fim_contrato date,ativo boolean not null default true,versao bigint not null default 1,criado_por uuid references utilizadores(id),atualizado_por uuid references utilizadores(id),criado_em timestamptz not null default now(),atualizado_em timestamptz not null default now(),constraint contrato_datas_validas check (fim_contrato is null or fim_contrato>=data_admissao));
create table if not exists ferias (id uuid primary key default gen_random_uuid(),funcionario_id uuid not null references funcionarios(id) on delete cascade,inicio date not null,fim date not null,dias integer not null check(dias>0),estado text not null default 'Disponível',versao bigint not null default 1,criado_por uuid references utilizadores(id),atualizado_por uuid references utilizadores(id),criado_em timestamptz not null default now(),atualizado_em timestamptz not null default now(),constraint ferias_datas_validas check(fim>=inicio));
create table if not exists auditoria (id uuid primary key default gen_random_uuid(),entidade text not null,entidade_id uuid,operacao text not null check(operacao in('CREATE','UPDATE','DELETE','SYNC')),utilizador_id uuid references utilizadores(id),dispositivo_id text,origem text not null default 'online' check(origem in('online','offline','sync')),antes jsonb,depois jsonb,criado_em timestamptz not null default now());
create table if not exists sincronizacao_eventos (id uuid primary key default gen_random_uuid(),dispositivo_id text not null,operacao_id text not null unique,entidade text not null,entidade_id uuid,operacao text not null check(operacao in('CREATE','UPDATE','DELETE')),versao_local bigint,recebido_em timestamptz not null default now(),processado_em timestamptz,status text not null default 'PENDENTE' check(status in('PENDENTE','PROCESSADO','CONFLITO','ERRO')),mensagem_erro text);
create index if not exists idx_funcionarios_departamento on funcionarios(departamento_id);create index if not exists idx_ferias_funcionario on ferias(funcionario_id);create index if not exists idx_auditoria_entidade on auditoria(entidade,entidade_id);create index if not exists idx_sync_status on sincronizacao_eventos(status);
insert into departamentos(nome) values('Administração'),('Serração'),('Vendas'),('Carpintaria'),('Manutenção'),('Mecânica'),('Seguranças') on conflict(nome) do nothing;
