'use client';
import {useEffect,useState} from 'react';
type Papel='Administrador'|'RH'|'Outro';type Utilizador={id:string;login:string;nome:string;papel:Papel;ativo:boolean};
export default function UtilizadoresPage(){const[users,setUsers]=useState<Utilizador[]>([]);const[login,setLogin]=useState('');const[nome,setNome]=useState('');const[papel,setPapel]=useState<Papel>('RH');const[senha,setSenha]=useState('');const[erro,setErro]=useState('');const[mensagem,setMensagem]=useState('');
 async function carregar(){try{const r=await fetch('/api/utilizadores',{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.erro||'Não foi possível carregar utilizadores.');setUsers(d.utilizadores||[]);}catch(e){setErro(e instanceof Error?e.message:'Não foi possível carregar utilizadores.');}}
 useEffect(()=>{carregar();},[]);
 async function adicionar(){setErro('');setMensagem('');if(!login.trim()||!nome.trim()||!senha)return setErro('Preencha login, nome e palavra-passe.');try{const r=await fetch('/api/utilizadores',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({login:login.trim(),nome:nome.trim(),papel,password:senha})});const d=await r.json();if(!r.ok)throw new Error(d.erro||'Não foi possível criar o utilizador.');await carregar();setLogin('');setNome('');setSenha('');setMensagem('Utilizador criado com sucesso.');}catch(e){setErro(e instanceof Error?e.message:'Não foi possível criar o utilizador.');}}
 return <main><div className="container"><section className="hero"><h1>Utilizadores e permissões</h1><p>Contas geridas pelo banco de dados e pela API protegida. Não existe armazenamento de utilizadores em localStorage.</p>{erro&&<p className="form-message" style={{color:'#dc2626'}}>{erro}</p>}{mensagem&&<p className="form-message">{mensagem}</p>}</section><section className="section"><div className="card"><h2>Novo utilizador</h2><div className="form-grid"><label>Login / ID<input value={login} onChange={e=>setLogin(e.target.value)} placeholder="Ex.: utilizador"/></label><label>Nome<input value={nome} onChange={e=>setNome(e.target.value)} placeholder="Nome do utilizador"/></label><label>Papel<select value={papel} onChange={e=>setPapel(e.target.value as Papel)}><option>Administrador</option><option>RH</option><option>Outro</option></select></label><label>Palavra-passe<input type="password" value={senha} onChange={e=>setSenha(e.target.value)} placeholder="Mínimo 4 caracteres"/></label></div><button className="primary-button" onClick={adicionar}>Criar utilizador</button></div></section><section className="section"><h2>Contas existentes</h2>{!users.length?<p className="empty-state">Nenhum utilizador disponível.</p>:<div className="table-wrapper"><table><thead><tr><th>Login / ID</th><th>Nome</th><th>Papel</th><th>Estado</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><strong>{u.login}</strong></td><td>{u.nome}</td><td><strong>{u.papel}</strong></td><td>{u.ativo?'Ativo':'Bloqueado'}</td></tr>)}</tbody></table></div>}</section></div></main>;
}
