'use client';
import { useEffect,useMemo,useState } from 'react';
type Funcionario={id:string;processo:string;nome:string;contacto:string;departamento:string;tipoContrato:string;admissao:string;fimContrato:string};
type Departamento={id:string;nome:string;totalFuncionarios?:number};
export default function DepartamentosPage(){const[funcionarios,setFuncionarios]=useState<Funcionario[]>([]);const[departamentos,setDepartamentos]=useState<Departamento[]>([]);const[filtro,setFiltro]=useState('Todos');const[novo,setNovo]=useState('');const[erro,setErro]=useState('');const[sucesso,setSucesso]=useState('');
 async function carregar(){try{setErro('');const[rF,rD]=await Promise.all([fetch('/api/funcionarios',{cache:'no-store'}),fetch('/api/departamentos',{cache:'no-store'})]);const df=await rF.json(),dd=await rD.json();if(!rF.ok)throw new Error(df.erro||'Não foi possível carregar funcionários.');if(!rD.ok)throw new Error(dd.erro||'Não foi possível carregar departamentos.');setFuncionarios(df.funcionarios||[]);setDepartamentos(dd.departamentos||[]);}catch(e){setErro(e instanceof Error?e.message:'Não foi possível carregar os dados.');}}
 useEffect(()=>{carregar();const id=window.setInterval(carregar,30000);return()=>window.clearInterval(id)},[]);
 const grupos=useMemo(()=>departamentos.map(d=>({departamento:d,lista:funcionarios.filter(f=>f.departamento===d.nome)})),[departamentos,funcionarios]);const gruposVisiveis=filtro==='Todos'?grupos:grupos.filter(g=>g.departamento.id===filtro);
 async function criar(e:React.FormEvent){e.preventDefault();setErro('');setSucesso('');try{const r=await fetch('/api/departamentos',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({nome:novo})});const d=await r.json();if(!r.ok)throw new Error(d.erro||'Não foi possível criar.');setNovo('');setSucesso('Departamento criado.');await carregar();}catch(e){setErro(e instanceof Error?e.message:'Não foi possível criar o departamento.');}}
 return <main><div className="container"><section className="hero"><h1>Departamentos</h1><p>Lista e contagens carregadas diretamente do banco de dados.</p>{erro&&<p className="form-message" style={{color:'#dc2626'}}>{erro}</p>}{sucesso&&<p className="form-message">{sucesso}</p>}</section><section className="section card"><form onSubmit={criar} style={{display:'flex',gap:12,flexWrap:'wrap',alignItems:'end'}}><label style={{flex:1,minWidth:240}}>Novo departamento<input value={novo} onChange={e=>setNovo(e.target.value)} placeholder="Nome do departamento" /></label><button type="submit">Adicionar</button></form><label className="filter-label">Filtrar departamento<select value={filtro} onChange={e=>setFiltro(e.target.value)}><option value="Todos">Todos</option>{departamentos.map(d=><option key={d.id} value={d.id}>{d.nome}</option>)}</select></label></section><section className="section"><div className="department-grid">{gruposVisiveis.map(({departamento,lista})=><div className="card department-panel" key={departamento.id}><div className="department-heading"><div><h2>{departamento.nome}</h2><span>{lista.length} funcionário(s)</span></div></div>{lista.length===0?<p className="empty-state">Nenhum funcionário neste departamento.</p>:<div className="table-wrapper"><table><thead><tr><th>Processo</th><th>Nome</th><th>Contacto</th><th>Contrato</th><th>Admissão</th></tr></thead><tbody>{lista.map(f=><tr key={f.id}><td>{f.processo}</td><td><strong>{f.nome}</strong></td><td>{f.contacto||'—'}</td><td><strong>{f.tipoContrato}</strong></td><td>{f.admissao||'—'}</td></tr>)}</tbody></table></div>}</div>)}{!gruposVisiveis.length&&<p className="empty-state">Nenhum departamento cadastrado.</p>}</div></section></div></main>;
}
