import { NextResponse } from 'next/server';
import { randomUUID } from 'node:crypto';
import { dbQuery, withTransaction } from '@/lib/server-db';
import { exigirPermissao, respostaAutorizacao } from '@/lib/server-auth';
import { adicionarDias, estadoFerias } from '@/lib/ferias';
export const runtime='nodejs';
type FeriasInput={funcionarioId?:string;inicio?:string;fim?:string;dias?:number;estado?:string};
const data=(v:unknown)=>typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v)?v:'';
const local=()=> (process.env.DATABASE_MODE||'local').toLowerCase()==='local';
const auditJson=(n:number)=>local()?`$${n}`:`$${n}::jsonb`;
function erro(code:string){const m:Record<string,string>={DADOS_INVALIDOS:'Funcionário, início e quantidade de dias são obrigatórios.',DATAS_INVALIDAS:'A data de fim calculada é inválida.',DIAS_INVALIDOS:'A quantidade de dias deve ser maior que zero.',FUNCIONARIO_INEXISTENTE:'Funcionário não encontrado ou inativo.'};return m[code]||'Não foi possível concluir a operação.';}
export async function GET(){try{await exigirPermissao('ferias');const result=await dbQuery(`select f.id,f.funcionario_id as "funcionarioId",u.processo,u.nome,u.departamento_id as "departamentoId",d.nome as departamento,f.inicio,f.fim,f.dias,f.estado,f.versao,f.criado_em as "criadoEm",f.atualizado_em as "atualizadoEm" from ferias f join funcionarios u on u.id=f.funcionario_id left join departamentos d on d.id=u.departamento_id order by f.inicio desc`);return NextResponse.json({ok:true,ferias:result.rows});}catch(error){if(error instanceof Error&&['UNAUTHORIZED','FORBIDDEN'].includes(error.message))return respostaAutorizacao(error);return NextResponse.json({ok:false,erro:'Não foi possível carregar as férias.'},{status:500});}}
export async function POST(request:Request){try{const sessao=await exigirPermissao('ferias');const input=await request.json() as FeriasInput;const funcionarioId=typeof input.funcionarioId==='string'?input.funcionarioId.trim():'';const inicio=data(input.inicio),dias=Number(input.dias||0);if(!funcionarioId||!inicio)throw new Error('DADOS_INVALIDOS');if(!Number.isInteger(dias)||dias<=0)throw new Error('DIAS_INVALIDOS');const fim=adicionarDias(inicio,dias);if(!fim||fim<inicio)throw new Error('DATAS_INVALIDAS');const result=await withTransaction(async client=>{const funcionario=await client.query('select id from funcionarios where id=$1 and ativo=true',[funcionarioId]);if(!funcionario.rows[0])throw new Error('FUNCIONARIO_INEXISTENTE');const id=randomUUID();const estado=estadoFerias(inicio,fim);const insert=await client.query(`insert into ferias(id,funcionario_id,inicio,fim,dias,estado,criado_por,atualizado_por,atualizado_em) values($1,$2,$3,$4,$5,$6,$7,$8,CURRENT_TIMESTAMP) returning id,funcionario_id as "funcionarioId",inicio,fim,dias,estado,versao,atualizado_em as "atualizadoEm"`,[id,funcionarioId,inicio,fim,dias,estado,sessao.utilizadorId,sessao.utilizadorId]);const novo=insert.rows[0];await client.query(`insert into auditoria(entidade,entidade_id,operacao,utilizador_id,dispositivo_id,origem,depois) values('ferias',$1,'CREATE',$2,$3,'online',${auditJson(4)})`,[novo.id,sessao.utilizadorId,request.headers.get('x-device-id')||null,JSON.stringify(novo)]);return novo;});return NextResponse.json({ok:true,ferias:result},{status:201});}catch(error){if(error instanceof Error&&['UNAUTHORIZED','FORBIDDEN'].includes(error.message))return respostaAutorizacao(error);if(error instanceof Error&&['DADOS_INVALIDOS','DATAS_INVALIDAS','DIAS_INVALIDOS','FUNCIONARIO_INEXISTENTE'].includes(error.message))return NextResponse.json({ok:false,erro:erro(error.message)},{status:400});return NextResponse.json({ok:false,erro:'Não foi possível registar as férias.'},{status:500});}}
