import { NextResponse } from 'next/server';
import { randomBytes, scryptSync } from 'node:crypto';
import { dbQuery, withTransaction } from '@/lib/server-db';
import { exigirPapel, respostaAutorizacao } from '@/lib/server-auth';
export const runtime='nodejs';

type Input={login?:string;nome?:string;papel?:'Administrador'|'RH'|'Outro';password?:string};
function hashPassword(password:string){const salt=randomBytes(16).toString('hex');const hash=scryptSync(password,salt,64).toString('hex');return `scrypt:${salt}:${hash}`;}
export async function GET(){try{await exigirPapel('Administrador');const r=await dbQuery(`select id,login,nome,papel,ativo,versao,criado_em as "criadoEm",atualizado_em as "atualizadoEm" from utilizadores order by nome`);return NextResponse.json({ok:true,utilizadores:r.rows});}catch(e){if(e instanceof Error&&['UNAUTHORIZED','FORBIDDEN'].includes(e.message))return respostaAutorizacao(e);return NextResponse.json({ok:false,erro:'Não foi possível carregar os utilizadores.'},{status:500});}}
export async function POST(request:Request){try{const sessao=await exigirPapel('Administrador');const input=await request.json() as Input;const login=input.login?.trim().toLowerCase()||'',nome=input.nome?.trim()||'',password=input.password||'',papel=input.papel;if(!login||!nome||!password||!['Administrador','RH','Outro'].includes(papel||''))return NextResponse.json({ok:false,erro:'Login, nome, papel e palavra-passe são obrigatórios.'},{status:400});if(password.length<4)return NextResponse.json({ok:false,erro:'A palavra-passe deve ter pelo menos 4 caracteres.'},{status:400});const novo=await withTransaction(async client=>{const r=await client.query(`insert into utilizadores(login,nome,papel,password_hash,ativo,versao,atualizado_em) values($1,$2,$3,$4,1,1,CURRENT_TIMESTAMP) returning id,login,nome,papel,ativo,versao,criado_em as "criadoEm",atualizado_em as "atualizadoEm"`,[login,nome,papel,hashPassword(password)]);const u=r.rows[0];await client.query(`insert into auditoria(entidade,entidade_id,operacao,utilizador_id,origem,depois) values('utilizador',$1,'CREATE',$2,'online',$3)`,[u.id,sessao.utilizadorId,JSON.stringify(u)]);return u;});return NextResponse.json({ok:true,utilizador:novo},{status:201});}catch(e){if(e instanceof Error&&['UNAUTHORIZED','FORBIDDEN'].includes(e.message))return respostaAutorizacao(e);if(e instanceof Error&&(e.message==='23505'||e.message.includes('UNIQUE constraint failed')))return NextResponse.json({ok:false,erro:'Este login já está registado.'},{status:409});console.error('POST /api/utilizadores',e);return NextResponse.json({ok:false,erro:'Não foi possível criar o utilizador.'},{status:500});}}
