'use client';
import { useEffect,useMemo,useState } from 'react';
import { adicionarDias,direitoAcumulado,diasUtilizadosReal,estadoFerias,resumoAnual,saldoRestante,type FuncionarioFerias } from '../../lib/ferias';
type HistoricoFerias=NonNullable<FuncionarioFerias['historico']>[number];
type Funcionario=FuncionarioFerias&{id:string;departamento:string;historico:HistoricoFerias[]};
function formatarData(data:string){if(!data)return '—';const[a,b,c]=data.split('-');return `${c}/${b}/${a}`;}
function estadoCor(estado:string){if(estado==='Em férias')return'status-active';if(estado==='Férias próximas')return'status-warning';if(estado==='Férias terminadas')return'status-muted';return'status-ok';}
export default function FeriasPage(){
 const[funcionarios,setFuncionarios]=useState<Funcionario[]>([]);const[processoSelecionado,setProcessoSelecionado]=useState('');const[inicio,setInicio]=useState('');const[quantidadeDias,setQuantidadeDias]=useState('');const[mensagem,setMensagem]=useState('');const[erro,setErro]=useState('');
 async function carregar(){try{const[rF,rH]=await Promise.all([fetch('/api/funcionarios',{cache:'no-store'}),fetch('/api/ferias',{cache:'no-store'})]);const df=await rF.json(),dh=await rH.json();if(!rF.ok)throw new Error(df.erro||'Não foi possível carregar funcionários.');if(!rH.ok)throw new Error(dh.erro||'Não foi possível carregar férias.');const hist:Record<string,HistoricoFerias[]>={};for(const x of dh.ferias||[]){(hist[x.funcionarioId]??=[]).push({inicio:x.inicio,fim:x.fim,dias:Number(x.dias),estado:x.estado});}setFuncionarios((df.funcionarios||[]).map((x:any)=>({processo:x.processo,nome:x.nome,tipoContrato:x.tipoContrato,admissao:x.admissao,fimContrato:x.fimContrato||'',diasUtilizados:0,inicioFerias:'',fimFerias:'',historico:hist[x.id]||[],id:x.id,departamento:x.departamento||'—'})));}catch(e){setErro(e instanceof Error?e.message:'Não foi possível carregar os dados.');}}
 useEffect(()=>{carregar();},[]);
 const funcionario=useMemo(()=>funcionarios.find(f=>f.processo===processoSelecionado),[funcionarios,processoSelecionado]);const direito=funcionario?direitoAcumulado(funcionario):0;const utilizados=funcionario?diasUtilizadosReal(funcionario):0;const restantes=funcionario?saldoRestante(funcionario):0;const dias=Math.max(0,Number.parseInt(quantidadeDias||'0',10)||0);const fim=inicio&&dias>0?adicionarDias(inicio,dias):'';const estadoPreview=fim?estadoFerias(inicio,fim):'Disponível';
 async function registarFerias(){setMensagem('');setErro('');if(!funcionario)return setErro('Selecione um funcionário.');if(!inicio)return setErro('Informe a data de início das férias.');if(dias<=0)return setErro('Informe uma quantidade de dias válida.');if(dias>restantes)return setErro(`O funcionário tem apenas ${restantes} dia(s) disponível(is).`);try{const r=await fetch('/api/ferias',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({funcionarioId:funcionario.id,inicio,fim,dias,estado:estadoPreview})});const d=await r.json();if(!r.ok)throw new Error(d.erro||'Não foi possível registar as férias.');await carregar();setInicio('');setQuantidadeDias('');setMensagem(`Férias registadas para ${funcionario.nome}: ${dias} dia(s), de ${formatarData(inicio)} a ${formatarData(fim)}.`);}catch(e){setErro(e instanceof Error?e.message:'Não foi possível registar as férias.');}}
 return <main><div className="container"><section className="hero"><h1>Controle de Férias</h1><p>Os registos são guardados no banco local SQLite através da API protegida.</p></section>
 <section className="section card"><h2>Registar férias</h2><div className="form-grid"><label>Funcionário<select value={processoSelecionado} onChange={e=>{setProcessoSelecionado(e.target.value);setErro('');}}><option value="">Selecione o funcionário</option>{funcionarios.map(f=><option key={f.id} value={f.processo}>{f.processo} — {f.nome}</option>)}</select></label><label>Data de início<input type="date" value={inicio} onChange={e=>setInicio(e.target.value)}/></label><label>Quantidade de dias<input type="number" min="1" max={restantes||undefined} value={quantidadeDias} onChange={e=>setQuantidadeDias(e.target.value)} placeholder="Ex.: 5"/></label></div>
 {funcionario&&<div className="grid" style={{marginTop:20}}><div className="card"><span className="card-label">Departamento</span><strong className="card-value" style={{fontSize:20}}>{funcionario.departamento}</strong></div><div className="card"><span className="card-label">Tipo de contrato</span><strong className="card-value" style={{fontSize:20}}>{funcionario.tipoContrato}</strong></div><div className="card"><span className="card-label">Direito acumulado</span><strong className="card-value">{direito} <small>dias</small></strong></div><div className="card"><span className="card-label">Saldo disponível</span><strong className="card-value">{restantes} <small>dias</small></strong></div></div>}
 <div className="card" style={{marginTop:16}}><strong>Resumo automático</strong><p style={{marginBottom:6}}>Dias solicitados: <strong>{quantidadeDias||'—'}</strong></p><p style={{marginBottom:6}}>Início: <strong>{inicio?formatarData(inicio):'—'}</strong></p><p style={{marginBottom:6}}>Fim calculado: <strong>{fim?formatarData(fim):'—'}</strong></p><p style={{margin:0}}>Estado previsto: <strong>{fim?estadoPreview:'Disponível'}</strong></p></div>
 {erro&&<p className="form-message" style={{color:'#dc2626'}}>{erro}</p>}{mensagem&&<p className="form-message">{mensagem}</p>}<button className="primary-button" type="button" onClick={registarFerias} disabled={!funcionarios.length}>Registar férias</button>{!funcionarios.length&&<p className="empty-state">Ainda não existem funcionários cadastrados.</p>}</section>
 <section className="section"><h2>Resumo dos funcionários</h2>{!funcionarios.length?<p className="empty-state">Nenhum funcionário disponível.</p>:<div className="table-wrapper"><table><thead><tr><th>Processo</th><th>Nome</th><th>Departamento</th><th>Direito acumulado</th><th>Utilizados</th><th>Saldo</th><th>Estado</th></tr></thead><tbody>{funcionarios.map(item=>{const d=direitoAcumulado(item),u=diasUtilizadosReal(item),r=saldoRestante(item),h=item.historico||[],ultimo=h[h.length-1];const estado=ultimo?estadoFerias(ultimo.inicio,ultimo.fim):'Disponível';return <tr key={item.id}><td>{item.processo}</td><td><strong>{item.nome}</strong></td><td><strong>{item.departamento}</strong></td><td>{d} dias</td><td>{u} dias</td><td><strong>{r} dias</strong></td><td><span className={estadoCor(estado)}>{estado}</span></td></tr>})}</tbody></table></div>}</section>
 <section className="section"><h2>Controlo anual de férias</h2><p>Direito, utilização e saldo calculados pelo motor central.</p>{funcionarios.length===0?<p className="empty-state">Nenhum funcionário disponível.</p>:<div className="history-list">{funcionarios.map(f=>{const resumo=resumoAnual(f),tg=resumo.reduce((s,i)=>s+i.ganhou,0),tu=resumo.reduce((s,i)=>s+i.utilizado,0),sf=resumo.length?resumo[resumo.length-1].saldoAcumulado:0;return <div className="card" key={`anual-${f.id}`}><h3 style={{marginTop:0}}>Processo {f.processo} — {f.nome}</h3><p><strong>{f.tipoContrato}</strong> · {f.departamento} · Direito adquirido: <strong>{tg} dias</strong> · Utilizado: <strong>{tu} dias</strong> · Saldo acumulado: <strong>{sf} dias</strong></p><div className="table-wrapper"><table><thead><tr><th>Ano</th><th>Dias ganhos</th><th>Dias utilizados</th><th>Saldo do ano</th><th>Saldo acumulado</th></tr></thead><tbody>{resumo.map(i=><tr key={`${f.id}-${i.ano}`}><td><strong>{i.ano}</strong></td><td>{i.ganhou} dias</td><td>{i.utilizado} dias</td><td>{i.saldoAno} dias</td><td><strong>{i.saldoAcumulado} dias</strong></td></tr>)}</tbody></table></div></div>})}</div>}</section>
 <section className="section"><h2>Histórico de férias</h2>{funcionarios.every(f=>!f.historico?.length)?<p className="empty-state">O histórico aparecerá aqui quando houver férias registadas.</p>:<div className="table-wrapper"><table><thead><tr><th>Processo</th><th>Funcionário</th><th>Departamento</th><th>Período</th><th>Dias</th><th>Estado</th></tr></thead><tbody>{funcionarios.flatMap(f=>(f.historico||[]).map((h,i)=><tr key={`${f.id}-${i}-${h.inicio}`}><td>{f.processo}</td><td><strong>{f.nome}</strong></td><td>{f.departamento}</td><td>{formatarData(h.inicio)} — {formatarData(h.fim)}</td><td>{h.dias}</td><td>{estadoFerias(h.inicio,h.fim)}</td></tr>))}</tbody></table></div>}</section>
 <section className="section card"><h2>Regras do novo motor</h2><p><strong>Permanente:</strong> 12 dias no ano de admissão e 30 dias nos anos completos seguintes.</p><p><strong>Contratado:</strong> 1 dia por mês de contrato contabilizado.</p><p><strong>Acumulação:</strong> o saldo não utilizado transita automaticamente para os anos seguintes.</p></section></div></main>;
}
